//
//  ExpenseInteractor.swift
//  Maexpense
//
//  Created by Ilyas Bintang Prayogi on 17/03/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class ExpenseInteractor {
}

// MARK: - Extensions -

extension ExpenseInteractor: ExpenseInteractorInterface {
}
