//
//  ExpenseViewController.swift
//  Maexpense
//
//  Created by Ilyas Bintang Prayogi on 17/03/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ExpenseViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: ExpensePresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
    }

}

// MARK: - Extensions -

extension ExpenseViewController: ExpenseViewInterface {
}
