//
//  ExpenseInterfaces.swift
//  Maexpense
//
//  Created by Ilyas Bintang Prayogi on 17/03/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol ExpenseWireframeInterface: WireframeInterface {
}

protocol ExpenseViewInterface: ViewInterface {
}

protocol ExpensePresenterInterface: PresenterInterface {
}

protocol ExpenseInteractorInterface: InteractorInterface {
}
