//
//  ExpenseInteractor.swift
//  Maexpense
//
//  Created by Ilyas Bintang Prayogi on 17/03/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import Alamofire

final class ExpenseInteractor {
}

// MARK: - Extensions -

extension ExpenseInteractor: ExpenseInteractorInterface {
    func fetchPortofolio(completion: @escaping (Portofolio) -> Void) {
        if let jsonUrl = Bundle.main.url(forResource: "userPortofolio", withExtension: "json"),
           let jsonData = try? Data(contentsOf: jsonUrl) {
            do {
                let portofolio = try JSONDecoder().decode(Portofolio.self, from: jsonData)
                completion(portofolio)
            }
            catch {
                print("Error decoding JSON:", error)
            }
        }
    }
    
    func fetchPortofolioService(completion: @escaping (AFResult<Portofolio>) -> Void) {
        let endpoint = "https://demo0726494.mockable.io/userPortofolio"

        AF.request(endpoint, method: .get)
            .validate()
            .responseDecodable(of: Portofolio.self) { response in
                completion(response.result)
        }
    }
}
