//
//  ExpenseInterfaces.swift
//  Maexpense
//
//  Created by Ilyas Bintang Prayogi on 17/03/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Alamofire

protocol ExpenseWireframeInterface: WireframeInterface {
    func goToDetail(data: MonthPortoDatum)
}

protocol ExpenseViewInterface: ViewInterface {
    func displayDonutChart(data: [MonthPortoDatum])
    func displayLineChart(data: [Int])
    func displayError(errorMsg: String)
}

protocol ExpensePresenterInterface: PresenterInterface {
    func presentPortofolio()
    func handleChartSelection(index: Int)
}

protocol ExpenseInteractorInterface: InteractorInterface {
    func fetchPortofolio(completion: @escaping (Portofolio) -> Void)
    func fetchPortofolioService(completion: @escaping (AFResult<Portofolio>) -> Void)
}
