//
//  DetailPresenter.swift
//  Maexpense
//
//  Created by Ilyas Bintang Prayogi on 18/03/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class DetailPresenter {
    
    // MARK: - Private properties -

    private unowned let view: DetailViewInterface
    private let interactor: DetailInteractorInterface
    private let wireframe: DetailWireframeInterface
    private let monthData: MonthPortoDatum

    // MARK: - Lifecycle -

    init(view: DetailViewInterface, interactor: DetailInteractorInterface, wireframe: DetailWireframeInterface, monthData: MonthPortoDatum) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
        self.monthData = monthData
    }
}

// MARK: - Extensions -

extension DetailPresenter: DetailPresenterInterface {
    func presentDetailPortofolio() {
        view.displayMonthData(data: monthData)
    }
    
}
