//
//  DetailViewController.swift
//  Maexpense
//
//  Created by Ilyas Bintang Prayogi on 18/03/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class DetailViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: DetailPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        presenter.presentDetailPortofolio()
    }

}

// MARK: - Extensions -

extension DetailViewController: DetailViewInterface {
    func displayMonthData(data: MonthPortoDatum) {
        
    }
    
}
