//
//  DetailWireframe.swift
//  Maexpense
//
//  Created by Ilyas Bintang Prayogi on 18/03/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class DetailWireframe: BaseWireframe<DetailViewController> {

    // MARK: - Module setup -

    init(monthData: MonthPortoDatum) {
        let moduleViewController = DetailViewController()
        super.init(viewController: moduleViewController)

        let interactor = DetailInteractor()
        let presenter = DetailPresenter(view: moduleViewController, interactor: interactor, wireframe: self, monthData: monthData)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension DetailWireframe: DetailWireframeInterface {
    func goBack() {
        navigationController?.popViewController(animated: true)
    }
    
}
