//
//  DetailInteractor.swift
//  Maexpense
//
//  Created by Ilyas Bintang Prayogi on 18/03/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class DetailInteractor {
}

// MARK: - Extensions -

extension DetailInteractor: DetailInteractorInterface {
}
